// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servidor;

namespace Servidor.Migrations
{
    [DbContext(typeof(TeatroDbContext))]
    [Migration("20220606125047_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Servidor.TeatroDbContext+Bilhete", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<int?>("sessoesid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("sessoesid");

                    b.ToTable("Bilhete");
                });

            modelBuilder.Entity("Servidor.TeatroDbContext+Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("bilheteId")
                        .HasColumnType("int");

                    b.Property<double>("contaVirtual")
                        .HasColumnType("float");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("bilheteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Servidor.TeatroDbContext+Espetaculo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dataFim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataInicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("preco")
                        .HasColumnType("float");

                    b.Property<string>("sinopse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("teatrosid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("teatrosid");

                    b.ToTable("Espetaculo");
                });

            modelBuilder.Entity("Servidor.TeatroDbContext+Sessao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("espetaculosid")
                        .HasColumnType("int");

                    b.Property<string>("horaFim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horaInicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("lugarDisponivel")
                        .HasColumnType("int");

                    b.Property<int>("lugarTotal")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("espetaculosid");

                    b.ToTable("Sessao");
                });

            modelBuilder.Entity("Servidor.TeatroDbContext+Teatro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("localizacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("telefone")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Teatro");
                });

            modelBuilder.Entity("Servidor.TeatroDbContext+Bilhete", b =>
                {
                    b.HasOne("Servidor.TeatroDbContext+Sessao", "sessoes")
                        .WithMany()
                        .HasForeignKey("sessoesid");

                    b.Navigation("sessoes");
                });

            modelBuilder.Entity("Servidor.TeatroDbContext+Cliente", b =>
                {
                    b.HasOne("Servidor.TeatroDbContext+Bilhete", "bilhetes")
                        .WithMany("Clients")
                        .HasForeignKey("bilheteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bilhetes");
                });

            modelBuilder.Entity("Servidor.TeatroDbContext+Espetaculo", b =>
                {
                    b.HasOne("Servidor.TeatroDbContext+Teatro", "teatros")
                        .WithMany()
                        .HasForeignKey("teatrosid");

                    b.Navigation("teatros");
                });

            modelBuilder.Entity("Servidor.TeatroDbContext+Sessao", b =>
                {
                    b.HasOne("Servidor.TeatroDbContext+Espetaculo", "espetaculos")
                        .WithMany()
                        .HasForeignKey("espetaculosid");

                    b.Navigation("espetaculos");
                });

            modelBuilder.Entity("Servidor.TeatroDbContext+Bilhete", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
